import type { Metadata } from "next";

import { AppHeader } from "@/components/AppHeader";
import { getRequestLocale } from "@/lib/request-locale";
import { absoluteUrl } from "@/lib/site";

type SearchParams = Promise<
  Record<string, string | string[] | undefined> | undefined
>;

const privacyCopy = {
  zh: {
    title: "隐私政策",
    intro:
      "本政策说明趣群岛 Circlist 在 MVP 阶段如何处理账号、提交内容和公开群组信息。",
    updated: "最后更新：2026 年 5 月 10 日",
    sections: [
      {
        title: "我们收集的信息",
        body: [
          "登录邮箱、基础账号资料以及用于保持登录状态的认证 cookie。",
          "你提交、认领或举报群组时填写的名称、简介、链接、二维码、地区、语言、群规和审核备注。",
          "公开页面访问中由托管平台、Supabase 或安全工具产生的基础日志。"
        ]
      },
      {
        title: "我们如何使用这些信息",
        body: [
          "用于登录、审核群组、维护公开目录、处理认领和举报。",
          "通过审核的群组信息可能被公开展示；未审核或被拒绝的提交不会作为公开列表展示。",
          "登录邮件会通过 Supabase 默认邮件服务或配置后的 Resend/SMTP 通道发送。"
        ]
      },
      {
        title: "二维码和群链接",
        body: [
          "提交者应只上传自己有权分享的二维码或链接。",
          "二维码可能过期或失效，Circlist 会根据举报、审核或维护状态调整展示。",
          "不要提交含有个人隐私、付款凭证、后台凭据或非公开邀请信息的图片。"
        ]
      },
      {
        title: "数据保留和删除",
        body: [
          "我们会在运营需要范围内保留账号、提交、审核和举报记录。",
          "如需删除你提交的内容或账号相关信息，可以通过项目维护者提供的联系渠道请求处理。"
        ]
      }
    ]
  },
  en: {
    title: "Privacy Policy",
    intro:
      "This policy explains how Circlist handles account, submission, and public community information during the MVP stage.",
    updated: "Last updated: May 10, 2026",
    sections: [
      {
        title: "Information We Collect",
        body: [
          "Sign-in email, basic account profile, and authentication cookies used to keep you signed in.",
          "Community names, descriptions, links, QR codes, region, language, rules, claims, reports, and review notes you submit.",
          "Basic logs generated by the hosting provider, Supabase, or security tooling when public pages are accessed."
        ]
      },
      {
        title: "How We Use Information",
        body: [
          "To support sign-in, review communities, maintain the public directory, and process claims or reports.",
          "Approved community information may be displayed publicly. Pending or rejected submissions are not listed publicly.",
          "Sign-in emails are sent through Supabase's default email service or a configured Resend/SMTP channel."
        ]
      },
      {
        title: "QR Codes and Group Links",
        body: [
          "Submitters should only upload QR codes or links they are allowed to share.",
          "QR codes may expire or become invalid, and Circlist may adjust visibility based on reports, reviews, or maintenance status.",
          "Do not submit images containing private personal data, payment proof, admin credentials, or non-public invite information."
        ]
      },
      {
        title: "Retention and Removal",
        body: [
          "We retain account, submission, review, and report records as needed to operate the service.",
          "To request removal of submitted content or account-related information, contact the project maintainer through the available support channel."
        ]
      }
    ]
  }
};

function firstParam(value: string | string[] | undefined): string | undefined {
  return Array.isArray(value) ? value[0] : value;
}

export const metadata: Metadata = {
  alternates: {
    canonical: absoluteUrl("/privacy")
  },
  title: "隐私政策 Privacy Policy",
  description: "趣群岛 Circlist 隐私政策。"
};

export default async function PrivacyPage({
  searchParams
}: {
  searchParams?: SearchParams;
}) {
  const params = await searchParams;
  const locale = await getRequestLocale(firstParam(params?.lang));
  const copy = privacyCopy[locale];

  return (
    <>
      <AppHeader locale={locale} pathname="/privacy" />
      <main className="mx-auto flex min-h-screen max-w-3xl flex-col gap-6 px-5 py-7">
        <section className="rounded-lg border border-ink/10 bg-white px-5 py-6 shadow-sm">
          <h1 className="text-3xl font-semibold leading-tight text-ink sm:text-4xl">
            {copy.title}
          </h1>
          <p className="mt-3 text-base leading-7 text-ink/68">{copy.intro}</p>
          <p className="mt-4 text-sm text-ink/45">{copy.updated}</p>
        </section>

        {copy.sections.map((section) => (
          <section
            className="rounded-lg border border-ink/10 bg-white p-5 shadow-sm"
            key={section.title}
          >
            <h2 className="text-xl font-semibold text-ink">{section.title}</h2>
            <ul className="mt-4 grid gap-3 text-sm leading-6 text-ink/68">
              {section.body.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </section>
        ))}
      </main>
    </>
  );
}
